LLDP_MAPPER_DICT = {
    'alcatel_aos': {'search_patterns': ['Alcatel-Lucent']},
    'alcatel_sros': {'search_patterns': ['Nokia', 'Alcatel']},
    'allied_telesis_awplus': {'search_patterns': ['AlliedWare Plus']},
    'apresia_aeos': {'search_patterns': ['Apresia']},
    'arista_eos': {'search_patterns': ['Arista', 'vEOS']},
    'ciena_saos': {'search_patterns': ['saos']},
    'cisco_asa': {'search_patterns': ['Cisco Adaptive Security Appliance',
                                    'Cisco ASA']},
    'cisco_ios': {'search_patterns': ['Cisco IOS Software',
                                    'Cisco Internetwork Operating System '
                                    'Software']},
    'cisco_nxos': {'search_patterns': ['Cisco Nexus Operating System', 'NX-OS']},
    'cisco_viptela': {'search_patterns': ['Viptela, Inc']},
    'cisco_wlc': {'search_patterns': ['CISCO_WLC']},
    'cisco_wlc_85': {'search_patterns': ['Cisco.*Wireless.*Controller']},
    'cisco_xe': {'search_patterns': ['Cisco IOS XE Software']},
    'cisco_xr': {'search_patterns': ['Cisco IOS XR']},
    'dell_force10': {'search_patterns': ['Real Time Operating System Software']},
    'dell_os10': {'search_patterns': ['Dell EMC Networking OS10.Enterprise']},
    'dell_os9': {'search_patterns': ['Dell Application Software Version:  9',
                                    'Dell Networking OS Version : 9']},
    'dell_powerconnect': {'search_patterns': ['PowerConnect']},
    'ericsson_ipos': {'search_patterns': ['Ericsson IPOS Version']},
    'extreme_exos': {'search_patterns': ['ExtremeXOS']},
    'extreme_netiron': {'search_patterns': ['(NetIron|MLX)']},
    'extreme_slx': {'search_patterns': ['SLX-OS Operating System']},
    'extreme_tierra': {'search_patterns': ['TierraOS Software']},
    'f5_linux': {'search_patterns': ['BIG-IP']},
    'f5_tmsh': {'search_patterns': ['BIG-IP']},
    'flexvnf': {'search_patterns': ['Versa FlexVNF']},
    'fortinet': {'search_patterns': ['FortiOS', 'FortiGate']},
    'hp_comware': {'search_patterns': ['HPE Comware', 'HP Comware']},
    'hp_procurve': {'search_patterns': ['Image stamp.*/code/build']},
    'huawei': {'search_patterns': ['Huawei Technologies',
                                    'Huawei Versatile Routing Platform Software']},
    'juniper_junos': {'search_patterns': ['JUNOS Software Release',
                                        'JUNOS .+ Software',
                                        'JUNOS OS Kernel',
                                        'JUNOS Base Version']},
    'linux': {'search_patterns': ['Linux']},
    'mellanox_mlnxos': {'search_patterns': ['Onyx', 'SX_PPC_M460EX']},
    'oneaccess_oneos': {'search_patterns': ['OneOS']},
    'paloalto_panos': {'search_patterns': ['model:\\s+PA']},
    'supermicro_smis': {'search_patterns': ['Super Micro Computer']},
    'ubiquiti_edgeswitch': {'search_patterns': ['EdgeSwitch']},
    'yamaha': {'search_patterns': ['Yamaha Corporation']}
 }


