name: syntax / build tests

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"

jobs:
  all-in-one-test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: setup env
        run: |
          pip3 install poetry
          poetry install --no-root

      # this will need tweaking on rules/etc so we can remove the -e 
      - name: run ruff tests
        run: poetry run ruff check -e nautobot_network_discovery/

      # basic local install to make sure we don't have any major issue
      - name: install project
        run: poetry install --only-root